"""Generate dictionary definitions for priority terms.

Reads KWIC concordance context and generates definition_brief + definition_long
for each term. Definitions are generated from corpus evidence following
WRITING_TEMPLATES.md voice rules.

This script contains the definitions directly (generated by Claude from KWIC context).
"""

import io
import json
import sqlite3
import sys
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

CORPUS_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = CORPUS_ROOT / "db" / "renmagic.db"
DEFS_PATH = CORPUS_ROOT / "data" / "definitions.json"


def load_definitions() -> list[dict]:
    """Load pre-generated definitions from JSON."""
    if DEFS_PATH.exists():
        return json.loads(DEFS_PATH.read_text(encoding="utf-8"))
    return []


def main():
    conn = sqlite3.connect(str(DB_PATH))
    defs = load_definitions()

    if not defs:
        print("ERROR: No definitions found at data/definitions.json")
        print("Generate definitions first, then run this script.")
        sys.exit(1)

    inserted = 0
    for d in defs:
        term = d["term"]
        brief = d.get("definition_brief", "")
        long_def = d.get("definition_long", "")

        if not brief:
            continue

        conn.execute("""
        UPDATE dictionary_terms SET
            definition_brief = ?,
            definition_long = ?,
            source_method = 'LLM_ASSISTED',
            confidence = 'MEDIUM',
            review_status = 'DRAFT',
            updated_at = datetime('now')
        WHERE term = ?
        """, (brief, long_def, term))

        if conn.execute("SELECT changes()").fetchone()[0] > 0:
            inserted += 1

    conn.commit()

    total_with = conn.execute(
        "SELECT COUNT(*) FROM dictionary_terms WHERE definition_brief IS NOT NULL AND definition_brief NOT LIKE '[GENERIC%'"
    ).fetchone()[0]

    print(f"=== DICTIONARY GENERATION ===")
    print(f"Definitions loaded: {len(defs)}")
    print(f"Inserted/updated: {inserted}")
    print(f"Total with definitions: {total_with}")

    conn.close()


if __name__ == "__main__":
    main()
